version: '3.8'

services:
  app:
    container_name: app
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    restart: always
    volumes:
      - .:/go/gen-insert

